sizes:
  type: 4
  token: 16
  username: 20
  password: 32
  file_name: 30

flags:
  message: 'MESG'
  file: 'FILE'
  register: 'CADT'
  alter_password: 'ALTS'
  delete_user: 'APGC'
  login: 'LOGN'
  logout: 'LOGT'
  success: 'SUSS'
  token: 'TOKN'
  end: 'endmessage'
